VALID_JSON_EXTENSIONS = [".json", ".jsonl"]
DEFAULT_ENCODING = "utf-8"
EMPTY_FILE = 0
MB_CONVERTER = 1024 * 1024
ISO8601_PATTERN = r'^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[+-]\d{2}:\d{2}|Z)?$)'
LOG_VERSION = "log_version"
OUTPUT_FILE_EXTENSION = ".jsonl"
TS_SCOPE = ['user', 'shared']
MAX_WRITE_ERRORS = 5