[project]
requires-python = ">=3.9"
dynamic = ["version"]

[tool.ruff]
line-length = 79
exclude = ["build", "dist", ".venv"]

[tool.ruff.lint]
ignore = []

[tool.setuptools.dynamic]
version = {attr = "thor2timesketch.__version__"}